### ISSUE TITLE
Area tracker

### ISSUE THREAD

**Issue by louisebeley** [AntSimi/py-eddy-tracker#72] opened 2021-03-18 12:34 UTC
Hello,
I have a few questions related to the area_tracker tracking method:
What are the different tracking criterion ?
Is there a criteria on the distance between two observations of the same eddy ?
Is there a criteria on the radius or the area ?
If there is a criteria on the distance, how does the tracker react if there is a missing observation? 

Are those criteria dependent of the time step used for the tracking?

 I searched for documentation on the Area_tracker but couldn't find any.

Thank you.

Best Regards,
Louise

**Comment by AntSimi** [comment] 2021-03-18 13:42
Hi,

I add today some short documentation about AreaTracker, which could be found [here](https://py-eddy-tracker.readthedocs.io/en/latest/_autosummary/py_eddy_tracker.featured_tracking.area_tracker.AreaTracker.html#py_eddy_tracker.featured_tracking.area_tracker.AreaTracker).

You have only one specific criterion : `cmin` which must be between [0,1], it's minimal value for cost function
Cost function is Intersection(contour1, contour2)/Union(contour1, contour2) => 1 -> exactly same contour, 0 -> No intersection

To manage missing time step you must used `VIRTUAL_LEGNTH_MAX` keyword [like in this example](https://py-eddy-tracker.readthedocs.io/en/latest/run_tracking.html).

If you want modify cost function, you need to inherit from EddiesObservations class and overwrite `tracking` method.

Antoine

**Comment by JeremyCollin** [comment] 2021-03-18 14:03
Hi Antoine thanks for this quick reply. 

I am currently working with Louise and we are modifying the code in order to track 12h observations from ROMS.

We were curious about some eddies with great lifetime tracked at 12h and not 24h. They appear to be small fast-advecting eddies that doesn't intersect at 24h.

Jérémy

**Comment by AntSimi** [comment] 2021-03-18 14:11
Di you use a classical detection or a detection based on okubo weiss?

**Comment by JeremyCollin** [comment] 2021-03-18 14:12
Okubo-weiss using Jonathan Gula version

**Comment by AntSimi** [comment] 2021-03-18 14:25
I didn't do detection with Okubo weiss, just i look at this field in this [example](https://py-eddy-tracker.readthedocs.io/en/latest/python_module/06_grid_manipulation/pet_okubo_weiss.html#sphx-glr-python-module-06-grid-manipulation-pet-okubo-weiss-py).
Did you compare the footprint of eddies with classical detection and your detection with Okubo Weiss one? It's something that i am interested to know and maybe build an example about that.
Most of the time i use AVISO output, so eddy size and movement are compliant with overlap method.

I you want to use AreaTracker with this time sampling (24h which didn't overlap in some case), i think you  need to build a new cost function to take benefit of overlap and manage quick eddies.
You could also use an [old classical tracking method](https://py-eddy-tracker.readthedocs.io/en/latest/_autosummary/py_eddy_tracker.featured_tracking.old_tracker_reference.CheltonTracker.html#py-eddy-tracker-featured-tracking-old-tracker-reference-cheltontracker) which are based only on ellips research area and similar amplitude and radius.

But is it a problem for you to work with 12h time step?

Antoine

**Comment by JeremyCollin** [comment] 2021-03-18 14:33
Comparing Okubo weiss with ssh will be done in a near future. We can let you know how this goes for sure.

and no, this not a blocking issue. We will work with 12h time stepping as new detected eddies are coherent structures. We just wanted to understand how area tracker works before going forward.

**Comment by AntSimi** [comment] 2021-03-18 14:33
Could you give me a quick summary of quantity in percent of observation which are stored in untracked/short/long after tracking?

**Comment by CoriPegliasco** [comment] 2021-03-18 14:42
Hi, @JeremyCollin you are right your eddies are too small to have an overlap after 24h. 
The overlap method (area_tracker) is designed for large eddies that move slowly. You can see here a large eddy moving very slow compared to its size: 
![image](https://user-images.githubusercontent.com/66008544/111644655-54433400-8800-11eb-915b-3375b074374a.png)

An idea could be to to advect the eddy contour from one day to another in case of rapid displacement (but I've never tried that).

**Comment by JeremyCollin** [comment] 2021-03-18 14:47
@AntSimi 
out of topic answer: (difference between 12h and 24h obeservations)
We used Okubo-Weiss interpolated at the different vertical levels (-2000, -1500, -1000, -500, -50) meters. Tracking was made with 10 days lifetime and 3 days of virtual observations. We found around 10% more eddies at the bottom and up to 50% near the surface. Most of these eddies have a short lifetime with more than 90% between 10 to 20 days. Less than 1% lived for more than 40 days. 

the appropriate answer : (I hope)
tracked : obs = 466802, untracked 317175, too short 743905

**Comment by AntSimi** [comment] 2021-03-18 15:31
When we work in global with AVISO1/4, classic statistics with AreaTracker look like that (for 30 years)
with more than 10 days for long with virtual=4
```bash
$ ncdump -h Anticyclonic.nc |grep "obs ="
	obs = 31971496 ;
$ ncdump -h Anticyclonic_untracked.nc |grep "obs ="
	obs = 433181 ;
$ ncdump -h Anticyclonic_track_too_short.nc |grep "obs ="
	obs = 2379818 ;
```
So statistics are very different, but we don't work with high resolution, we have around 1.3% of untracked and 7.5% of short

**Comment by AntSimi** [comment] 2021-03-19 07:37
Another question did you look at radius distribution for each category (long/short/untracked) ?

**Comment by JeremyCollin** [comment] 2021-03-23 12:59
Hi Antoine,
sorry for the late reply but here is some plots of eddy effective radius distribution from AreaTracker with 10 days lifetime at least and 3 days of virtual observations. Detection was performed on ROMS 2km grid Okubo-Weiss at 50 m depth with 12h outputs in the north Atlantic for over a year. We can see the number of observations in the y-axis related to the radius (km) x-axis. 
![Anticyclonic_pdf_effective_radius](https://user-images.githubusercontent.com/47636703/112149713-8fb67780-8bdf-11eb-8cd6-2e668449d46c.png)
![Cyclonic_pdf_effective_radius](https://user-images.githubusercontent.com/47636703/112149715-8fb67780-8bdf-11eb-8dee-1b698468c81d.png)

I am actually surprised to see that radius are rather small, what do you think ?

**Comment by AntSimi** [comment] 2021-03-23 14:11
I am also suprised by distribution, if you want i could give you distribution for aviso/cmems on similar area(if you give  me area specification).
You could also with GUIEddy (in py eddy tracker) look at eddy paths interactively, to look if area-tracker miss somethings.

I am still afraid that OW minimize area/radius (Still to check) or maybe model resolution prevents big eddies.

**Comment by JeremyCollin** [comment] 2021-03-25 07:15
When looking at animations detection seems correct. We are looking at 70W - 10 E  x 35 N - 70 N area. We should soon look closer at ADT detection for comparison.

**Comment by AntSimi** [comment] 2021-03-25 08:58
With [following code](https://gist.github.com/AntSimi/d28b53c7d9916e10fcda8665d5bb6fd9), i extract from a global atlas your area and get those distribution:
### Speed radius distribution
![image](https://user-images.githubusercontent.com/36040805/112446019-0e322700-8d50-11eb-9262-c3b7a4511f3c.png)
### Effective radius distribution
![image](https://user-images.githubusercontent.com/36040805/112446039-125e4480-8d50-11eb-8dbe-0f9d6cf7d46c.png)

**Comment by JeremyCollin** [comment] 2021-04-16 09:30
Hi Antoine,
indeed detection using adt reveals larger structures. We are still investigating whether OW detection could be helpful in our vertical approach.

Jonathan started to develop our branch from e767238 revision and then merged master version of py-eddy-tracker into it. We are currently running some tests to ensure our devs are correct. We are comparing detection (OW) and tracking (area_tracker) and we find small differences in contour, shape error, radius and location of eddies at detection, and also a little less tracked eddies (0.1%). Was there any change on detection contour, shape, center, radius between master and e767238 or is it our code that brought an issue ?

Thanks
![Effective_radius_histogram](https://user-images.githubusercontent.com/47636703/115004445-1987f680-9ea7-11eb-888b-ec0b341df318.png)
![Speed_radius_histogram](https://user-images.githubusercontent.com/47636703/115004449-1a208d00-9ea7-11eb-9b58-f2b18d5cd78d.png)
![Lifetime_histogram](https://user-images.githubusercontent.com/47636703/115004450-1a208d00-9ea7-11eb-9816-78e877b80538.png)

**Comment by AntSimi** [comment] 2021-04-16 09:57
Right now i haven't obvious reason to explain differences.
Is it for one day or larger period?
In order to found reasons, maybe work on only one day.
To isolate eddy difference you could use [match method](https://py-eddy-tracker.readthedocs.io/en/stable/python_module/02_eddy_identification/pet_sla_and_adt.html#scatter-plot) with high cmin.

**Comment by JeremyCollin** [comment] 2021-04-16 10:13
Well this is for a larger period. I hoped there was a change in contour definition but unfortunately we'll have to look closer at 1 day detection then.

**Comment by AntSimi** [comment] 2021-04-16 10:48
How did you ran identification? With a python script or with eddyid?

**Comment by AntSimi** [comment] 2021-04-16 10:58
Another question number of eddy are the same for one day?

**Comment by JeremyCollin** [comment] 2021-04-16 11:41
> How did you ran identification? With a python script or with eddyid?

EddyTracking area_tracker.yaml

> Another question number of eddy are the same for one day?

yes they are exactly the same number for detection

**Comment by AntSimi** [comment] 2021-04-16 12:01
My question was about identification and not tracking

**Comment by JeremyCollin** [comment] 2021-04-16 12:07
python modified script 
`    a, c = h.eddy_identification('ow', 'u', 'v', date, step=1e-11,
                 z_min=-0.3 * 1e-10,
                 z_max=-0.2 * 1e-10,
                 pixel_limit=(20, 10000), shape_error=55,
                 force_height_unit='µm',force_speed_unit='m/s',
                 vorticity_name='vrt')
`

**Comment by AntSimi** [comment] 2021-04-16 12:09
Maybe instead of radius could you compare speed_area and effective_area to avoid possible differences

**Comment by louisebeley** [comment] 2021-04-16 14:06
Hi antoine, when we compare speed_area and effective_area, we have an aproximate error of 0.1%.
![Effective_area_histogram](https://user-images.githubusercontent.com/80892931/115036390-c2494c80-9ecd-11eb-965f-5b8000a7441a.png)

![Speed_area_histogram](https://user-images.githubusercontent.com/80892931/115036096-7c8c8400-9ecd-11eb-8ba0-851beae2a09f.png)

**Comment by AntSimi** [comment] 2021-04-16 15:45
Same value with radius?
The most direct thing to understand the difference is to load 2 identification file use match function with cmin around .99 (will return all index with high match) and after extract with index and reverse option to keep only different eddy.
And look at those eddies (grographic, amplitude distribution, radius distribution, ...).

Something like that:
```python
i_0, i_1, c = d0.match(d1, cmin=0.99)
d0_ = d0.index(i_0, reverse=True)
d1_ = d1.index(i_1, reverse=True)
```

**Comment by AntSimi** [comment] 2021-04-16 20:21
I wrote a small bash script in order to reproduce your problem [here](https://gist.github.com/AntSimi/8ef292af97147ad838c7823980f93593), i could see some difference with this example.
I will try to find change and check if it's wanted.

**Comment by AntSimi** [comment] 2021-04-22 20:47
After some tests if found some informations:
new_version => last version
old_version => commit of your fork

Detection changes begin after [commit a1515b](https://github.com/AntSimi/py-eddy-tracker/commit/a1515bdb1dfd7ea9466b2692a45b50948b751705), like it could see in comparison (at the end of the message).

Since this commit the default value of `nb_step_to_be_mle` is set to 0, which stop any eddy detection with two local maxima. But you use [eddy_identification method directly](https://github.com/AntSimi/py-eddy-tracker/blob/master/src/py_eddy_tracker/dataset/grid.py#L588), so you are not concern by that ...

In reference the commit, where you start your fork,:
```bash
[ref] old_version/Anticyclonic_20160515.nc -> 65 obs
[0] commit_5cbc1165b3e2ac469763e72d1e4018982bce7bfd/Anticyclonic_20160515.nc -> 65 obs
[1] commit_a1515bdb1dfd7ea9466b2692a45b50948b751705/Anticyclonic_20160515.nc -> 64 obs
[2] new_version/Anticyclonic_20160515.nc -> 64 obs
          nomatch    50 <= low < 80  intermediate    100 <= high    multi_match      parent          twin          complex    
[ 0]     0.0% (0)       0.0% (0)       0.0% (0)      100.0% (65)     0.0% (0)       0.0% (0)       0.0% (0)       0.0% (0)    
[ 1]     1.5% (1)       3.1% (2)       3.1% (2)      92.3% (60)      0.0% (0)       0.0% (0)       0.0% (0)       0.0% (0)    
[ 2]     1.5% (1)       3.1% (2)       3.1% (2)      92.3% (60)      0.0% (0)       0.0% (0)       0.0% (0)       0.0% (0)    
     Point of view of study dataset
          nomatch    50 <= low < 80  intermediate    100 <= high    multi_match      parent          twin          complex    
[ 0]     0.0% (0)       0.0% (0)       0.0% (0)      100.0% (65)     0.0% (0)       0.0% (0)       0.0% (0)       0.0% (0)    
[ 1]     0.0% (0)       3.1% (2)       3.1% (2)      93.8% (60)      0.0% (0)       0.0% (0)       0.0% (0)       0.0% (0)    
[ 2]     0.0% (0)       3.1% (2)       3.1% (2)      93.8% (60)      0.0% (0)       0.0% (0)       0.0% (0)       0.0% (0)
```

In reference, last version available at this time:
```bash
[ref] new_version/Anticyclonic_20160515.nc -> 64 obs
[0] commit_a1515bdb1dfd7ea9466b2692a45b50948b751705/Anticyclonic_20160515.nc -> 64 obs
[1] commit_5cbc1165b3e2ac469763e72d1e4018982bce7bfd/Anticyclonic_20160515.nc -> 65 obs
[2] old_version/Anticyclonic_20160515.nc -> 65 obs
          nomatch    50 <= low < 80  intermediate    100 <= high    multi_match      parent          twin          complex    
[ 0]     0.0% (0)       0.0% (0)       0.0% (0)      100.0% (64)     0.0% (0)       0.0% (0)       0.0% (0)       0.0% (0)    
[ 1]     0.0% (0)       3.1% (2)       3.1% (2)      93.8% (60)      0.0% (0)       0.0% (0)       0.0% (0)       0.0% (0)    
[ 2]     0.0% (0)       3.1% (2)       3.1% (2)      93.8% (60)      0.0% (0)       0.0% (0)       0.0% (0)       0.0% (0)    
     Point of view of study dataset
          nomatch    50 <= low < 80  intermediate    100 <= high    multi_match      parent          twin          complex    
[ 0]     0.0% (0)       0.0% (0)       0.0% (0)      100.0% (64)     0.0% (0)       0.0% (0)       0.0% (0)       0.0% (0)    
[ 1]     1.5% (1)       3.1% (2)       3.1% (2)      92.3% (60)      0.0% (0)       0.0% (0)       0.0% (0)       0.0% (0)    
[ 2]     1.5% (1)       3.1% (2)       3.1% (2)      92.3% (60)      0.0% (0)       0.0% (0)       0.0% (0)       0.0% (0)
```

**Closed** 2021-09-16 11:13 UTC
